### ISSUE TITLE
0.2.11 Not Working, 0.2.10 & 0.2.9 Did In ember-in-viewport

### ISSUE THREAD

**Issue by MatthewPringle** [snewcomer/intersection-observer-admin#17]
I have been using ember-in-viewport and recently updated to 3.7.2 from 3.6.2. My code runs in Cordova as an iOS app.

I have found that updating to 3.7.2 breaks my app and it no longer uses the observer.

https://github.com/DockYard/ember-in-viewport/issues/228

Version 0.2.9 / 0.2.10 of intersection-observer-admin works fine, version 0.2.11 doesn't work at all.

**Comment by MatthewPringle** [comment]
It would seem to be this line which causes the issue https://github.com/snewcomer/intersection-observer-admin/commit/c19b7f590adc4c90badcf30680b978b6ce0e5fa3

**From:**
if (isIntersecting || intersectionRatio > threshold) {

**To:**
if (isIntersecting || intersectionRatio >= threshold) {

**Comment by MatthewPringle** [comment]
Can confirm broken in Chrome and Safari on desktop, Safari browser on iOS and this is not a Cordova problem.

**Comment by snewcomer** [comment]
Awesome!  I am going to guess those platforms implement it slightly differently.  Since this didn't work, I have no problem reverting!  0.2.12

**Comment by snewcomer** [comment]
This was closed in the #18
