### ISSUE TITLE
Needs a new release

### ISSUE THREAD

**Issue by pichfl** [snewcomer/intersection-observer-admin#23]
The change made in this commit https://github.com/snewcomer/intersection-observer-admin/commit/aabb5790955b31dc7a0ae0f6e8d5e0ba408e5ea6 needs to be released. 

The currently released version does not play well with the `{{hash }}` helper in Ember (which is used by https://github.com/elwayman02/ember-scroll-modifiers and possibly others), because `hasOwnProperty()` should never be called from the object but from the generic prototype like is done in the commit above.

**Comment by snewcomer** [comment]
closed!  0.2.13 published.  Thanks for reminding me!
