### ISSUE TITLE
removeCallback API

### ISSUE THREAD

**Issue by ygongdev** [snewcomer/intersection-observer-admin#25]
Is it possible to add the `remove` equivalent to the `enter` and `exit` callbacks?

It is possible for us to want to remove the listener when limiting the number of times a callback can fire without `unobserving` the `element`.

**Comment by ygongdev** [comment]
I took a peek into the source code, looks like we need something more robust than `removeElement` that targets removing certain `values/options` from the `registry`'s `element`.

**Comment by ygongdev** [comment]
@snewcomer FYI

**Comment by snewcomer** [comment]
👋  @ygongdev!  I'd be down for adding something like an LRU cache like utility.  However, we need to figure out what we are targeting.  The one problem I think I am seeing is `observing` and the registry are tied.  So if we purged something, we might lose the ability to look it up.  Or is that what you desire?  You want an intersection for a purged element to be a noop even if it comes into view?

**Comment by ygongdev** [comment]
Yeah if I can create an analogy, it would be like an `removeEventListener` for an `addEventListener`.
Our initial intention is to prevent memory leak and optimize performance.

After a certain criteria is met, we want to remove a specific callback listener, e.g `enter`, but we don't want to completely unobserve the element because it might still have to listen for another callback, e.g `exit`.

**Comment by snewcomer** [comment]
I see!  Well I might suggest it might give us little impact to remove "parts" of the "value" for a specific "key" (element) that is stored in a WeakMap.  For example, removing a reference to a function that you pass likely gives us little benefit in terms of memory space.  But I'd love to hear your thoughts!  I might not be understanding your scenario fully.

We use this for extremely high loads for a few years on a long lived (desktop like) application and haven't seen any terrible violations of memory space.

**Comment by ygongdev** [comment]
Actually after going through some reviews, we realized we could handle this on our end. I'll close this. Thanks!
